# Projetando Redes Neurais com Tensor Flow e otimizando com Keras


- Esse notebook tem como finalidade registrar as anotações sobre o estudo da biblioteca keras


### Introdução ao Keras

- importando o keras

In [1]:
import keras 
import numpy as np
print(keras.__version__)

3.6.0


# models

### Model class

- é um grupo de camadas em um objeto de treino, model possui dois parâmetros a entrada e a saida

In [ ]:
keras.Model()

### Functional API

- o uso é bastante simples, você cria uma camada,com suas expecificações de quantidade de nós,modelo de ativação, neste caso é o 'relu' e em seguida conecta essa camada com a próxima

In [ ]:
inputs = keras.Input(shape=(37,)) #camada de entrada
inputs

x = keras.layers.Dense(32,activation='relu')(inputs)
outputs = keras.layers.Dense(5,activation='softmax')(x)
model = keras.Model(inputs=inputs,outputs=outputs)

- vejamos um modelo mais complexo

In [ ]:

inputs2 = keras.Input(shape=(None,None,3))
processed2 = keras.layers.RandomCrop(width=128,height=128)(inputs2)

conv2 = keras.layers.Conv2D(filters=32,kernel_size=3)(processed2)
pooling2 = keras.layers.GlobalAveragePooling2D()(conv2)
feature2 = keras.layers.Dense(10)(pooling2)

full_model2 = keras.Model(inputs2,feature2)
backbone = keras.Model(processed2,conv2)
activations = keras.Model(conv2,feature2)


- no código acima temos três modelos (full_model2,backbone e activations) o modelo completo (full_mode2) tem:
    * inputs2 - 3 neuronios de entrada. 
    * processed2 - camada de processamento que reduz o tamanho da imagem para 128 x 128 píxels.
    * conv2 - camada convolucional que utiliza um kernel de 3x3 para multiplicar individualmente os píxels e seleciona o maior e adiciona em uma matriz de 32 x 32  
    * pooling2 - camada que coleta a transversal de um array bi-dimencional e armazena em um objeto
    * feature2 - camada Densa que efetua o treino de fato usando um modelo neural como o perceptrom

- full_model2 - Modelo Completo com todas as camadas de processamento e camadas de treino
- backbone -  extração de dados e parâmetros sobre as camadas iniciais de processamento
- activations - usada na extração de parâmetros sobre as camadas de treino 

# Usando Models e Subclasses

In [27]:
class MyModel(keras.Model):
    def __init__(self):
        super().__init__()
        self.dense1 = keras.layers.Dense(32, activation='relu')
        self.dense2 = keras.layers.Dense(5,activation='softmax')

    def call(self,inputs):
        x = self.dense1(inputs)
        return self.dense2(x)
    

model3 = MyModel()        

In [ ]:
class MyModel(keras.Model):
    def __init__(self):
        super().__init__()
        self.dense1 = keras.layers.Dense(32, activation="relu")
        self.dense2 = keras.layers.Dense(5, activation="softmax")
        self.dropout = keras.layers.Dropout(0.5)

    def call(self, inputs, training=False):
        x = self.dense1(inputs)
        x = self.dropout(x, training=training)
        return self.dense2(x)

model4 = MyModel()

# usando Classes Sequenciais

- outro método para a montagem de modelos é usando modelos sequenciais, onde a a saíde de uma camada automaticamente será conectada na entrada da camada seguinte

In [ ]:
model5 = keras.Sequential([
    keras.Input(shape=(None,None,3)),
    keras.layers.Conv2D(filters=32,kernel_size=3),
]) 

### método summary() | summary method

# API de camadas | keras layers API

In [28]:
import keras
from keras import layers

layer = layers.Dense(32, activation='relu')
inputs = keras.random.uniform(shape=(10, 20))
outputs = layer(inputs)

In [29]:
layer.weights

[<KerasVariable shape=(20, 32), dtype=float32, path=dense_12/kernel>,
 <KerasVariable shape=(32,), dtype=float32, path=dense_12/bias>]

### Camadas de Ativação | Activation Layers Functions

#### relu function

In [30]:
x = [-10, -5, 0.0, 5, 10]
keras.activations.relu(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  0.,  0.,  5., 10.], dtype=float32)>

- relu seleciona apenas os valores positivos de um array

#### sigmoid function

In [42]:
x = [-10, -5, 0.0, 5, 10]
keras.activations.sigmoid(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([4.539787e-05, 6.692851e-03, 5.000000e-01, 9.933072e-01,
       9.999546e-01], dtype=float32)>

- sigmoid so aceita valores decimais e retorna sempre valores entre -1 e 1 realizando o seguinte cálculo:
sigmoid(x) = 1 / (1 + exp(-x)).

#### softmax function

In [ ]:
keras.activations.softmax(x, axis=-1)

### Camadas de Pre-processamento | Preprocessing layers

#### Image preprocessing layer

#### resizing class

In [ ]:
keras.layers.Resizing(
    height,
    width,
    interpolation="bilinear",
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    fill_mode="constant",
    fill_value=0.0,
    data_format=None,
    **kwargs
)

#### rescaling class

In [ ]:
keras.layers.Rescaling(scale, offset=0.0, **kwargs)